apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  {{- if not .Values.ingress.enabled }}  
  annotations:
    strimzi.io/use-connector-resources: "true"
  {{- end }} 
spec:
  {{- if not .Values.createimage.enabled }}
  image: "{{ .Values.image }}:{{ .Values.imageTag }}"
  {{- end }}
  {{- if .Values.createimage.enabled }}
  build:
    output:
      type: docker
      image: "{{ .Values.image }}:{{ .Values.imageTag }}"
      pushSecret: dockerhub-creds
    plugins:
{{- with .Values.createimage.plugins }}
{{- toYaml . | nindent 6 }}
{{- end }}
  {{- end }}
  bootstrapServers: {{ .Values.bootstrapServers }}
  replicas: {{ .Values.replicaCount }}
  config:
    version: {{ .Values.version }}
    group.id: {{ .Values.groupid }}
    offset.storage.topic: {{ .Values.topic.offset }}
    config.storage.topic: {{ .Values.topic.config }}
    status.storage.topic: {{ .Values.topic.status }}
    offset.storage.replication.factor: "{{ .Values.topic.offsetfactor | default "-1" }}"
    config.storage.replication.factor: "{{ .Values.topic.configfactor | default "-1" }}"
    status.storage.replication.factor: "{{ .Values.topic.statusfactor | default "-1" }}"
    auto.create.topics.enable: false
    ssl.endpoint.identification.algorithm: HTTPS
    ssl.enabled.protocols: TLSv1.2,TLSv1.1,TLSv1
{{- if .Values.customSettings }}
{{- toYaml .Values.customSettings | nindent 4 }}
{{- end }}
  tls:
    trustedCertificates: []
  authentication:
    type: plain
    username: {{ .Values.username }}
    passwordSecret:
      secretName: {{ .Values.name }}-password
      password: password
  logging:
    type: inline
    loggers:
      connect.root.logger.level: {{ .Values.loglevel | default "INFO" }}
  template:
    pod:
      imagePullSecrets:
        - name: dockerhub-creds
      metadata:
        labels:
          {{- include "dsre-charts-common.labels" . | nindent 10 }}
          {{- include "dsre-charts-common.datadog-labels" . | nindent 10 }}            