apiVersion: v2
appVersion: 0.0.3
description: Scales Kubernetes worker nodes within autoscaling groups.
engine: gotpl
maintainers:
  - email: thisurawijesekera@gmail.com
    name: TS
name: cluster-autoscaler
sources:
  - https://github.com/thisurawijesekera/helm-chart-registry/tree/master/charts/cluster-autoscaler
type: application
version: 0.0.3
