apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-kafka-creds
  namespace: {{ .Values.namespace }}
  annotations:
    {{- include "dsre-charts-common.external-secrets-annotations" . | nindent 8 }}  
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.name }}-password   
  data: 
  - secretKey: password
    remoteRef:
      key: {{ required "A valid value for externalSecrets.key(vault path) need!" .Values.externalSecrets.key }} 
      property: {{ required "A valid value for externalSecrets.property(vault key) need!" .Values.externalSecrets.property }}        
