name: CI [ts-helm-charts] 

on: 
  pull_request:
    types: 
      - opened
      - reopened
      - labeled
      - synchronize
    branches: 
      - master
  
concurrency:
  group: ts-kube-platform
  cancel-in-progress: true

jobs:
  Scan:
    name: Terrascan
    uses: thisurawijesekera/reusable-workflows/.github/workflows/terrascans.yaml@master
    with:
      TYPE: helm
      VERSION: v3
      POLICY: k8s
      PATH: .
    secrets: inherit
    
  lint-test:
    name: Lint & Test
    uses: thisurawijesekera/reusable-workflows/.github/workflows/helm_test.yaml@master
    secrets: inherit
    needs: 
      - Scan     
