name: CI [dsre-helm-charts] 

on: 
  pull_request:
    types: 
      - opened
      - reopened
      - labeled
      - synchronize
    branches: 
      - master

concurrency:
  group: dsre-kube-platform
  cancel-in-progress: true

jobs:
  Scan:
    name: Terrascan
    uses: SyscoCorporation/dim-dsre-reusable-workflows/.github/workflows/terrascan.yaml@master
    with:
      TYPE: helm
      VERSION: v3
      POLICY: k8s
      PATH: .
    secrets: inherit

  lint-test:
    name: Lint & Test
    uses: SyscoCorporation/dim-dsre-reusable-workflows/.github/workflows/helm_test.yaml@master
    secrets: inherit
    needs: 
      - Scan     
