name: CD [TS-helm-charts] Release
  
on:
  push:
    branches:
      - master 

concurrency:
  group: ts-kube-platform
  cancel-in-progress: true

permissions:
  contents: write
 
jobs:
  Version: 
    name: Chart Version, Package and Publish
    uses: thisurawijesekera/reusable-workflows/.github/workflows/helm_release.yaml@master
    with:
      REPO_URL: https://raw.githubusercontent.com/thisurawijesekera/helm-chart-registry/gh-pages
    secrets: inherit       
